name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: "init repository"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: "Install dependencies"
        run: npm install
        
      - name: "Build app"
        run: npm run build
      
      - name: "install ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: "Install DPL"
        run: gem install dpl

      - name: "Deploy to Heroku"
        run: dpl --provider-heroku --app-${{secrets.HEROKU_APP}} --api-key-{{secrets.HEROKU_API_KEY}} --skip_cleanup=true

      # - name: "Deploy to Heroku"
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: ${{secrets.HEROKU_APP}}
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}